language: cpp

matrix:
    include:
      - os: osx
        osx_image: xcode10.2
        env: LIBMESH_VERSION=1.4.1
      - os: linux
        dist: xenial
        env: LIBMESH_VERSION=1.4.1
      - os: linux
        dist: xenial
        env: CI_BUILD_DOCS=true LIBMESH_VERSION=1.4.1
#        - os: linux
#          dist: xenial
#          env: LIBMESH_VERSION=1.3.1
#        - os: osx
#          osx_image: xcode10.2
#          env: LIBMESH_VERSION=1.3.1
#        - os: linux
#          dist: xenial
#          env: LIBMESH_VERSION=1.5.0
      - os: osx
        osx_image: xcode10.2
        env: LIBMESH_VERSION=1.5.0

before_install:
  - ci/build_dependencies.sh

install:
  - ci/get_libmesh.sh

script:
  - ci/build_mast.sh
  -

deploy:
  provider: script
  script: bash doc/deploy_docs.sh
  skip_cleanup: true
  on:
    branch: master
