language: cpp

matrix:
    include:
        - os: linux
          dist: xenial
          env: LIBMESH_VERSION=1.3.1
        - os: linux
          dist: xenial
          env: LIBMESH_VERSION=1.4.1
        - os: linux
          dist: xenial
          env: LIBMESH_VERSION=1.5.0

before_install:
  - ci/build_dependencies.sh

install:
  - ci/get_libmesh.sh

before_script:
  - export MAST_INSTALL_DIR=${HOME}/mast
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake ..
    -DCMAKE_INSTALL_PREFIX=${MAST_INSTALL_DIR}
    -DCMAKE_C_COMPILER=mpicc
    -DCMAKE_CXX_COMPILER=mpic++
    -DCMAKE_Fortran_COMPILER=mpifort
    -DlibMesh_DIR=/usr/local
    -DPETSc_DIR=/usr/lib/petscdir/3.6.2/x86_64-linux-gnu-real
    -DSLEPc_DIR=/usr/lib/slepcdir/3.6.1/x86_64-linux-gnu-real
    -DEIGEN3_ROOT=/usr/include/eigen3
    -DBOOST_ROOT=/usr
    -DBUILD_DOC=ON
    -DENABLE_DOT=OFF
    -DENABLE_GCMMA=OFF
    -DENABLE_SNOPT=OFF

script:
  - make -j 2
  - make -j 2 doc_doxygen
  - cd ${TRAVIS_BUILD_DIR}

deploy:
  provider: script
  script: bash doc/deploy_docs.sh
  skip_cleanup: true
  on:
    branch: master
