language: cpp
dist: xenial

before_install:
- sudo apt-get install -y gfortran wget m4
- sudo apt-get install -y openmpi-bin libopenmpi-dev
- sudo apt-get install -y libpetsc3.6 libpetsc3.6.2-dev
- sudo apt-get install -y libslepc3.6 libslepc3.6.1-dev libparpack2-dev
- sudo apt-get install -y libboost-all-dev
- sudo apt-get install -y libeigen3-dev

install:
- cd ${HOME}
- wget https://github.com/MASTmultiphysics/mast-ci-packages/releases/download/libmesh-1.3.1-1.deb/libmesh-1.3.1-1.deb
- sudo apt install ./libmesh-1.3.1-1.deb

before_script:
- export MAST_INSTALL_DIR=${HOME}/mast
- cd ${TRAVIS_BUILD_DIR}
- mkdir build
- cd build
- cmake ..
    -DCMAKE_INSTALL_PREFIX=${MAST_INSTALL_DIR}
    -DCMAKE_C_COMPILER=mpicc
    -DCMAKE_CXX_COMPILER=mpic++
    -DCMAKE_Fortran_COMPILER=mpifort
    -DlibMesh_DIR=/usr/local
    -DPETSc_DIR=/usr/lib/petscdir/3.6.2/x86_64-linux-gnu-real
    -DSLEPc_DIR=/usr/lib/slepcdir/3.6.1/x86_64-linux-gnu-real
    -DEIGEN3_ROOT=/usr/include/eigen3
    -DBOOST_ROOT=/usr
    -DBUILD_DOC=OFF
    -DENABLE_DOT=OFF
    -DENABLE_GCMMA=OFF
    -DENABLE_NPSOL=OFF

script: make -j 2